import { generateContent } from "../ai/gemini.server";
import { loadBusinessMemory, compressMemoryForPrompt } from "./business-memory.server";
import { getSupabaseServer } from "../supabase.server";

/**
 * Report Generator Engine
 *
 * Generates Weekly and Monthly executive reports using full business memory.
 * Stores reports in the reports table for historical access.
 * Reuses the executive briefing pattern but with deeper analysis.
 */

export interface GeneratedReport {
  title: string;
  period: "Daily" | "Weekly" | "Monthly";
  content: string;
  summary: string;
  reportDate: string;
}

export async function generateReport(params: {
  businessId: string;
  period: "Daily" | "Weekly" | "Monthly";
}): Promise<GeneratedReport> {
  const supabase = getSupabaseServer();
  const memory = await loadBusinessMemory(params.businessId);
  const context = compressMemoryForPrompt(memory);

  const today = new Date();
  const dateStr = today.toISOString().split("T")[0];
  const periodLabel = params.period === "Daily"
    ? `Daily Brief — ${today.toLocaleDateString("en-IN", { month: "short", day: "numeric", year: "numeric" })}`
    : params.period === "Weekly"
    ? `Weekly Growth Report — Week ${getWeekNumber(today)}`
    : `Monthly Executive Summary — ${today.toLocaleDateString("en-IN", { month: "long", year: "numeric" })}`;

  const depthInstruction = params.period === "Monthly"
    ? "Provide a comprehensive strategic analysis with trend insights, competitive landscape shifts, and quarterly projections. Include sections for: Executive Summary, Growth Trajectory, Competitive Intelligence, Opportunity Pipeline, Revenue Impact Assessment, and Strategic Recommendations for next month."
    : params.period === "Weekly"
    ? "Provide a focused weekly digest with score changes, new opportunities surfaced, competitor movements, and top 3 actions for next week."
    : "Provide a brief daily snapshot with today's growth score, any score changes, and the single most important action.";

  const prompt = `
${context}

Generate a ${params.period} executive report for "${memory.business.name}".

${depthInstruction}

Write the report in clean markdown format.
Start with the title "${periodLabel}".
Use specific numbers from the business context — scores, competitor names, opportunity revenues.
Keep the tone executive-level: strategic, data-driven, actionable.
Do not use generic e-commerce advice. Every recommendation must tie to the specific data above.
`;

  try {
    const content = await generateContent(prompt, {
      systemInstruction: "You are Nexora AI's Report Generator. You produce executive-grade growth reports for e-commerce businesses. Every statement must be grounded in the provided business data. Use markdown formatting. Be concise but thorough.",
    });

    // Generate a summary (first 200 chars of content, cleaned)
    const summaryText = content.replace(/^#.*\n/gm, "").replace(/\*\*/g, "").trim().slice(0, 200) + "...";

    // Store in database
    if (params.businessId !== "dev-business-id") {
      try {
        await supabase.from("reports").insert({
          business_id: params.businessId,
          title: periodLabel,
          period: params.period,
          content: content.trim(),
          summary: summaryText,
          report_date: dateStr,
        });
      } catch (e) {
        console.warn("Could not save report:", e);
      }
    }

    return {
      title: periodLabel,
      period: params.period,
      content: content.trim(),
      summary: summaryText,
      reportDate: dateStr,
    };
  } catch (error) {
    console.error("Report generation failed:", error);
    const fallbackContent = `# ${periodLabel}\n\n## Growth Score: ${memory.scores.seo.score + memory.scores.aeo.score + memory.scores.geo.score > 0 ? Math.round((memory.scores.seo.score + memory.scores.aeo.score + memory.scores.geo.score) / 3) : "N/A"}/100\n\n### Key Metrics\n- SEO: ${memory.scores.seo.score}/100\n- AEO: ${memory.scores.aeo.score}/100\n- GEO: ${memory.scores.geo.score}/100\n\n### Competitors Tracked: ${memory.competitors.length}\n${memory.competitors.map(c => `- ${c.name} (${c.threatLevel} threat)`).join("\n")}\n\n### Open Opportunities: ${memory.opportunities.filter(o => o.status === "open").length}\n${memory.opportunities.filter(o => o.status === "open").slice(0, 3).map(o => `- ${o.title} (₹${o.revenue}/mo)`).join("\n")}\n\n---\n*Report generated by Nexora AI*`;

    return {
      title: periodLabel,
      period: params.period,
      content: fallbackContent,
      summary: `Growth report for ${memory.business.name}. ${memory.opportunities.filter(o => o.status === "open").length} open opportunities tracked.`,
      reportDate: dateStr,
    };
  }
}

function getWeekNumber(d: Date): number {
  const oneJan = new Date(d.getFullYear(), 0, 1);
  return Math.ceil(((d.getTime() - oneJan.getTime()) / 86400000 + oneJan.getDay() + 1) / 7);
}
